<?php include 'src/views/layouts/header.phtml'; ?>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 d-flex flex-column" style="min-height: 0;">
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 mb-3 border-bottom">
		<h1 class="h2">Register</h1>
	</div>
	<div class="d-flex align-items-stretch mb-3" style="max-height: 75%;">
		<div class="card flex-fill" style="max-height: 100%;">
			<div class="card-header">
				Club
			</div>
			<ul class="list-group list-group-flush" style="overflow-y: scroll;">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 1
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 2
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 3
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 4
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 5
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 6
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 7
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 8
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 9
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 10
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 11
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 12
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 13
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 14
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 15
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 16
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
			</ul>
		</div>
		<div class="card flex-fill mx-3" style="max-height: 100%;">
			<div class="card-header">
				Club
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 1
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 2
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 3
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 4
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 5
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 6
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 7
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 8
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 9
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 10
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 11
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<!-- <li class="list-group-item d-flex justify-content-between align-items-center">
					User 12
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 13
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 14
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 15
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 16
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li> -->
			</ul>
		</div>
		<div class="card flex-fill" style="max-height: 100%;">
			<div class="card-header">
				Club
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 1
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 2
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 3
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 4
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 5
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 6
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 7
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 8
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 9
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 10
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 11
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<!-- <li class="list-group-item d-flex justify-content-between align-items-center">
					User 12
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 13
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 14
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 15
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 16
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li> -->
			</ul>
		</div>
		<!-- <div class="card" style="width: 30%;">
			<div class="card-header">
				Toast Club
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Lauren Blundell
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Kate Rimmer
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Debbie Blundell
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Arlo Adams
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					George Crook
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
			</ul>
		</div> -->
		<!-- <div class="card" style="width: 30%;">
			<div class="card-header">
				After School Club
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Lauren Blundell
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Kate Rimmer
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Debbie Blundell
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					Arlo Adams
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					George Crook
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					George Crook
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					George Crook
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
			</ul>
		</div> -->
	</div>
</main>
<?php include 'src/views/layouts/footer.phtml'; ?>