<?php include 'src/views/layouts/header.phtml'; ?>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 d-flex flex-column" style="min-height: 0;">
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 mb-3 border-bottom">
		<h1 class="h2">Register</h1>
	</div>
	<div class="d-flex h-100 mb-3">
		<div class="card flex-fill">
			<div class="card-header">
				Breakfast Club
			</div>
			<ul class="list-group list-group-flush d-flex flex-grow-1" style="height:0px; overflow-y: scroll;">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 1
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 2
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 3
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 4
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 5
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 6
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 7
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 8
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 9
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 10
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 11
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 12
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 13
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 14
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 15
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 16
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
			</ul>
		</div>
		<div class="card flex-fill mx-3">
			<div class="card-header">
				Toast Club
			</div>
			<ul class="list-group list-group-flush d-flex flex-grow-1" style="height:0px; overflow-y: auto;">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 1
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 2
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 3
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 4
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 5
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 6
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 7
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 8
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 9
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 10
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 11
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 12
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 13
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 14
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 15
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 16
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 14
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 15
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 16
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 14
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 15
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 16
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 14
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 15
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 16
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
			</ul>
		</div>
		<div class="card flex-fill">
			<div class="card-header">
				After School Club
			</div>
			<ul class="list-group list-group-flush d-flex flex-grow-1" style="height:0px; overflow-y: auto;">
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 1
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 2
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 3
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 4
					<button type="button" class="btn btn-sm btn-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 5
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 6
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					User 7
					<button type="button" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-check"></i></button>
				</li>
			</ul>
		</div>
	</div>
</main>
<?php include 'src/views/layouts/footer.phtml'; ?>