<?php include 'src/views/layouts/header.phtml'; ?>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 d-flex flex-column" style="min-height: 0;">
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 mb-3 border-bottom">
		<h1 class="h2">Register</h1>
	</div>
	<div class="d-flex h-100 mb-3">
		<div class="card flex-fill">
			<div class="card-header">
				Breakfast Club
			</div>
			<ul class="list-group list-group-flush d-flex flex-grow-1" style="height:0px; overflow-y: scroll;">
				<?php foreach($data['breakfast_club'] as $child) { ?>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					<?=$child['name'];?>
					<button type="button" class="btn btn-sm <?=($child['present'] ? 'btn-success' : 'btn-outline-success')?>"><i class="fa-solid fa-check"></i></button>
				</li>
				<?php } ?>
			</ul>
		</div>
		<div class="card flex-fill mx-3">
			<div class="card-header">
				Toast Club
			</div>
			<ul class="list-group list-group-flush d-flex flex-grow-1" style="height:0px; overflow-y: auto;">
				<?php foreach($data['toast_club'] as $child) { ?>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					<?=$child['name'];?>
					<button type="button" class="btn btn-sm <?=($child['present'] ? 'btn-success' : 'btn-outline-success')?>"><i class="fa-solid fa-check"></i></button>
				</li>
				<?php } ?>
			</ul>
		</div>
		<div class="card flex-fill">
			<div class="card-header">
				After School Club
			</div>
			<ul class="list-group list-group-flush d-flex flex-grow-1" style="height:0px; overflow-y: auto;">
				<?php foreach($data['after_school_club'] as $child) { ?>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					<?=$child['name'];?>
					<button type="button" class="btn btn-sm <?=($child['present'] ? 'btn-success' : 'btn-outline-success')?>"><i class="fa-solid fa-check"></i></button>
				</li>
				<?php } ?>
			</ul>
		</div>
	</div>
</main>
<?php include 'src/views/layouts/footer.phtml'; ?>