<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Whizz Kids</title>
	<!-- Stylesheets -->
	<link rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="../node_modules/@fortawesome/fontawesome-free/css/fontawesome.min.css">
	<link rel="stylesheet" href="../node_modules/@fortawesome/fontawesome-free/css/brands.min.css">
	<link rel="stylesheet" href="../node_modules/@fortawesome/fontawesome-free/css/solid.min.css">
	<link rel="stylesheet" href="../assets/css/core-styles.css">
	<!-- Javascript -->
	<script src="../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</head>
<body class="d-flex flex-column">
	<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
		<a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Whizz Kids</a>
		<button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-nav">
			<div class="nav-item text-nowrap">
				<a class="nav-link px-3" href="#">Sign out</a>
			</div>
		</div>
	</header>
	<div class="container-fluid d-flex flex-grow-1">
		<div class="row d-flex flex-grow-1">
			<!-- Start of Sidebar -->
			<nav id="sidebarMenu" class="col-2 d-md-block bg-light sidebar collapse">
				<div class="position-sticky pt-3">
					<ul class="nav flex-column">
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="/">Dashboard</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/register">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/rota">Rota</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Accounts</a>
						</li>
					</ul>
					<hr>
					<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">Administration</h6>
					<ul class="nav flex-column mb-2">
						<li class="nav-item">
							<a class="nav-link" href="#">Pricing</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">User Management</a>
						</li>
					</ul>
				</div>
			</nav>
			<!-- Start of content -->