<table class="table table-bordered">
	<thead>
		<tr>
			<th colspan="7" class="bg-light">
				<div class="d-flex justify-content-between align-items-center">
					<button class="btn btn-sm btn-secondary" data-date="<?=$previous?>"><i class="fa-solid fa-chevron-left"></i></button>
					<?=$calendarHeader?>
					<button class="btn btn-sm btn-secondary" data-date="<?=$next?>"><i class="fa-solid fa-chevron-right"></i></button>
				</div>
			</th>
		</tr>
		<tr>
			<th class="text-center">Sun</th>
			<th class="text-center">Mon</th>
			<th class="text-center">Tue</th>
			<th class="text-center">Wed</th>
			<th class="text-center">Thu</th>
			<th class="text-center">Fri</th>
			<th class="text-center">Sat</th>
		</tr>
	</thead>
	<tbody>
		<?php 
			$currentDateNumber = 1;
			for($count = 0; $count < $totalRows; $count++) { ?>
		<tr>
		<?php for($dayCount = 0; $dayCount < 7; $dayCount++) {
				if($daysToSkip != 0 || $currentDateNumber == 0) {
					$daysToSkip--;
		?>
					<td class="calendar-date"></td>
		<?php 	} else { ?>
					<td class="calendar-date <?=(date("Y-m-d") == substr($selectedDate, 0, -2).$currentDateNumber ? 'bg-info': '')?>"><?=$currentDateNumber?></td>
		<?php 
				$currentDateNumber = ($currentDateNumber == $totalDaysInMonth || $daysToSkip > 0 ? 0 : $currentDateNumber+1);
				}
			}
		?>
		</tr>
		<?php } ?>
	</tbody>
</table>